#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Jun 28 18:46:14 CST 2026
maven-metadata-aliyunmaven.xml.lastUpdated=1782643574748
maven-metadata-central.xml.lastUpdated=1782643574748
maven-metadata-huaweicloud.xml.lastUpdated=1782643574749
