#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Jun 04 20:30:37 CST 2026
maven-metadata-aliyunmaven.xml.lastUpdated=1780576237978
maven-metadata-central.xml.lastUpdated=1780576237978
maven-metadata-huaweicloud.xml.lastUpdated=1780576237978
