#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu May 21 00:03:44 CST 2026
maven-metadata-aliyunmaven.xml.lastUpdated=1779293024554
maven-metadata-central.xml.lastUpdated=1779293024551
maven-metadata-huaweicloud.xml.lastUpdated=1779293024555
