-- Oracle schema script
-- Note: create the CAMPUS schema/user before executing this script.
SET search_path TO campus;

create table campus.sys_role (
  id bigint generated by default as identity primary key,
  role_code varchar2(64 char) not null,
  role_name varchar2(128 char) not null,
  permissions clob,
  is_active number(1) default 1 not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (role_code),
  check (is_active in (0, 1)),
  check (is_deleted in (0, 1))
);

merge into campus.sys_role t
using (
  select 'student' as role_code, '普通学生' as role_name from dual
  union all
  select 'cadre' as role_code, '班团骨干' as role_name from dual
  union all
  select 'teacher_admin' as role_code, '管理老师' as role_name from dual
  union all
  select 'college_leader' as role_code, '学院领导' as role_name from dual
) s
on (t.role_code = s.role_code)
when not matched then
  insert (role_code, role_name)
  values (s.role_code, s.role_name);

create table campus.sys_user (
  id bigint generated by default as identity primary key,
  student_no varchar2(32 char) not null,
  full_name varchar2(64 char) not null,
  status varchar2(32 char) default 'active' not null,
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (student_no),
  check (status in ('active', 'disabled')),
  check (is_deleted in (0, 1)),
  check (ext_json is json)
);

create table campus.sys_user_role (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  role_id bigint not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (user_id, role_id),
  foreign key (user_id) references campus.sys_user(id),
  foreign key (role_id) references campus.sys_role(id)
);

create table campus.sys_user_auth (
  id bigint generated by default as identity primary key,
  student_no varchar2(32 char) not null,
  login_method varchar2(32 char) not null,
  wechat_openid varchar2(64 char),
  password_hash varchar2(255 char),
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (student_no, login_method),
  unique (wechat_openid),
  foreign key (student_no) references campus.sys_user(student_no),
  check (login_method in ('wechat', 'password')),
  check (
    (login_method = 'wechat' and wechat_openid is not null and password_hash is null)
    or
    (login_method = 'password' and password_hash is not null and wechat_openid is null)
  ),
  check (is_deleted in (0, 1))
);

create table campus.sys_student_ext (
  student_no varchar2(32 char) primary key,
  major_name varchar2(128 char) not null,
  grade_year number(10) not null,
  class_name varchar2(128 char) not null,
  political_status varchar2(64 char) not null,
  party_status varchar2(64 char) not null,
  id_card_cipher blob,
  id_card_hash varchar2(64 char),
  home_address_cipher blob,
  home_address_hash varchar2(64 char),
  phone_cipher blob,
  phone_hash varchar2(64 char),
  gpa number(4, 2),
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  foreign key (student_no) references campus.sys_user(student_no),
  check (is_deleted in (0, 1)),
  check (ext_json is json)
);

create table campus.sys_operation_log (
  id bigint generated by default as identity primary key,
  module_code varchar2(64 char) not null,
  business_type varchar2(64 char),
  business_id bigint,
  operation_type varchar2(64 char) not null,
  operation_desc clob,
  operator_user_id bigint,
  trace_id varchar2(128 char),
  request_uri varchar2(512 char),
  request_method varchar2(16 char),
  request_ip varchar2(64 char),
  user_agent varchar2(512 char),
  log_level varchar2(16 char) default 'info' not null,
  result_status varchar2(16 char) default 'success' not null,
  error_message clob,
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  foreign key (operator_user_id) references campus.sys_user(id),
  check (log_level in ('info', 'warn', 'error', 'audit')),
  check (result_status in ('success', 'fail', 'partial')),
  check (ext_json is json)
);

create index idx_sys_operation_log_user on campus.sys_operation_log(operator_user_id, created_at desc);
create index idx_sys_operation_log_biz on campus.sys_operation_log(module_code, business_type, business_id);
create index idx_sys_operation_log_trace on campus.sys_operation_log(trace_id);

create table campus.file_object (
  id bigint generated by default as identity primary key,
  purpose varchar2(64 char) not null,
  original_name varchar2(256 char) not null,
  mime_type varchar2(128 char),
  size_bytes bigint not null,
  sha256 varchar2(64 char),
  storage_provider varchar2(64 char) not null,
  storage_path varchar2(512 char) not null,
  uploaded_by bigint,
  uploaded_at timestamp(6) with time zone default systimestamp not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  foreign key (uploaded_by) references campus.sys_user(id),
  check (is_deleted in (0, 1))
);

create index idx_file_object_purpose on campus.file_object(purpose);
create index idx_file_object_sha256 on campus.file_object(sha256);

create table campus.kb_policy (
  id bigint generated by default as identity primary key,
  title varchar2(256 char) not null,
  summary clob,
  content clob,
  source_type varchar2(32 char) default 'manual' not null,
  source_url varchar2(512 char),
  attachment_file_id bigint,
  is_published number(1) default 1 not null,
  published_at timestamp(6) with time zone,
  created_by bigint,
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  check (source_type in ('manual', 'crawl', 'import')),
  check (is_published in (0, 1)),
  check (is_deleted in (0, 1)),
  check (ext_json is json),
  foreign key (attachment_file_id) references campus.file_object(id),
  foreign key (created_by) references campus.sys_user(id)
);

create index idx_kb_policy_published on campus.kb_policy(is_published, published_at);

create table campus.kb_faq (
  id bigint generated by default as identity primary key,
  question varchar2(512 char) not null,
  answer clob not null,
  source_policy_id bigint,
  is_published number(1) default 1 not null,
  created_by bigint,
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  foreign key (source_policy_id) references campus.kb_policy(id),
  foreign key (created_by) references campus.sys_user(id),
  check (is_published in (0, 1)),
  check (is_deleted in (0, 1)),
  check (ext_json is json)
);

create index idx_kb_faq_published on campus.kb_faq(is_published, created_at);

create table campus.kb_keyword (
  id bigint generated by default as identity primary key,
  keyword varchar2(64 char) not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (keyword)
);

create table campus.kb_policy_keyword (
  id bigint generated by default as identity primary key,
  policy_id bigint not null,
  keyword_id bigint not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (policy_id, keyword_id),
  foreign key (policy_id) references campus.kb_policy(id),
  foreign key (keyword_id) references campus.kb_keyword(id)
);

create table campus.kb_faq_keyword (
  id bigint generated by default as identity primary key,
  faq_id bigint not null,
  keyword_id bigint not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (faq_id, keyword_id),
  foreign key (faq_id) references campus.kb_faq(id),
  foreign key (keyword_id) references campus.kb_keyword(id)
);

create table campus.kb_keyword_search_history (
  id bigint generated by default as identity primary key,
  search_user_id bigint,
  keyword_id bigint,
  search_keyword varchar2(128 char) not null,
  search_scope varchar2(32 char) default 'all' not null,
  search_channel varchar2(32 char) default 'miniprogram' not null,
  result_count number(10) default 0 not null,
  session_token varchar2(128 char),
  client_ip varchar2(64 char),
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  foreign key (search_user_id) references campus.sys_user(id),
  foreign key (keyword_id) references campus.kb_keyword(id),
  check (search_scope in ('all', 'policy', 'faq', 'notice', 'template')),
  check (search_channel in ('miniprogram', 'admin', 'api', 'other')),
  check (result_count >= 0),
  check (ext_json is json)
);

create index idx_kb_keyword_search_user on campus.kb_keyword_search_history(search_user_id, created_at desc);
create index idx_kb_keyword_search_keyword on campus.kb_keyword_search_history(keyword_id, created_at desc);
create index idx_kb_keyword_search_text on campus.kb_keyword_search_history(search_keyword, created_at desc);

create table campus.kb_qa_ticket (
  id bigint generated by default as identity primary key,
  ask_user_id bigint not null,
  question_text clob not null,
  status varchar2(32 char) default 'open' not null,
  matched_faq_id bigint,
  handled_by bigint,
  handled_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  check (status in ('open', 'answered', 'closed')),
  foreign key (ask_user_id) references campus.sys_user(id),
  foreign key (matched_faq_id) references campus.kb_faq(id),
  foreign key (handled_by) references campus.sys_user(id)
);

create index idx_kb_qa_ticket_status on campus.kb_qa_ticket(status, created_at);

create table campus.party_flow (
  id bigint generated by default as identity primary key,
  flow_code varchar2(64 char) not null,
  flow_name varchar2(128 char) not null,
  flow_type varchar2(32 char) not null,
  is_active number(1) default 1 not null,
  created_by bigint,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (flow_code),
  check (flow_type in ('party', 'league')),
  check (is_active in (0, 1)),
  check (is_deleted in (0, 1)),
  foreign key (created_by) references campus.sys_user(id)
);

create table campus.party_flow_node (
  id bigint generated by default as identity primary key,
  flow_id bigint not null,
  seq_no number(10) not null,
  node_code varchar2(64 char) not null,
  node_name varchar2(128 char) not null,
  description clob,
  expected_days number(10),
  reminder_offset_days number(10),
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (flow_id, seq_no),
  unique (flow_id, node_code),
  foreign key (flow_id) references campus.party_flow(id),
  check (is_deleted in (0, 1))
);

create index idx_party_flow_node_flow on campus.party_flow_node(flow_id, seq_no);

create table campus.party_student_progress (
  id bigint generated by default as identity primary key,
  student_user_id bigint not null,
  flow_id bigint not null,
  current_node_id bigint,
  status varchar2(32 char) default 'in_progress' not null,
  started_at timestamp(6) with time zone,
  updated_node_at timestamp(6) with time zone,
  next_deadline_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (student_user_id, flow_id),
  check (status in ('not_started', 'in_progress', 'paused', 'completed')),
  check (is_deleted in (0, 1)),
  foreign key (student_user_id) references campus.sys_user(id),
  foreign key (flow_id) references campus.party_flow(id),
  foreign key (current_node_id) references campus.party_flow_node(id)
);

create index idx_party_student_progress_deadline on campus.party_student_progress(next_deadline_at);

create table campus.party_reminder_task (
  id bigint generated by default as identity primary key,
  progress_id bigint not null,
  node_id bigint not null,
  due_at timestamp(6) with time zone not null,
  channel varchar2(32 char) default 'miniprogram' not null,
  status varchar2(32 char) default 'pending' not null,
  sent_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  check (channel in ('miniprogram', 'sms', 'email')),
  check (status in ('pending', 'sent', 'canceled', 'failed')),
  foreign key (progress_id) references campus.party_student_progress(id),
  foreign key (node_id) references campus.party_flow_node(id)
);

create index idx_party_reminder_due on campus.party_reminder_task(status, due_at);

create table campus.notice_tag_dict (
  id bigint generated by default as identity primary key,
  tag_code varchar2(64 char) not null,
  tag_name varchar2(64 char) not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (tag_code),
  check (is_deleted in (0, 1))
);

create table campus.notice_item (
  id bigint generated by default as identity primary key,
  title varchar2(256 char) not null,
  content clob,
  source_type varchar2(32 char) default 'manual' not null,
  source_name varchar2(128 char),
  source_url varchar2(512 char),
  attachment_file_id bigint,
  publish_at timestamp(6) with time zone,
  created_by bigint,
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  check (source_type in ('manual', 'crawl', 'import')),
  check (is_deleted in (0, 1)),
  check (ext_json is json),
  foreign key (attachment_file_id) references campus.file_object(id),
  foreign key (created_by) references campus.sys_user(id)
);

create index idx_notice_item_publish on campus.notice_item(publish_at desc);

create table campus.notice_item_tag (
  id bigint generated by default as identity primary key,
  notice_id bigint not null,
  tag_id bigint not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (notice_id, tag_id),
  foreign key (notice_id) references campus.notice_item(id),
  foreign key (tag_id) references campus.notice_tag_dict(id)
);

create table campus.notice_item_keyword (
  id bigint generated by default as identity primary key,
  notice_id bigint not null,
  keyword_id bigint not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (notice_id, keyword_id),
  foreign key (notice_id) references campus.notice_item(id),
  foreign key (keyword_id) references campus.kb_keyword(id)
);

create index idx_notice_item_keyword_keyword on campus.notice_item_keyword(keyword_id, notice_id);

create table campus.notice_delivery (
  id bigint generated by default as identity primary key,
  notice_id bigint not null,
  channel varchar2(32 char) not null,
  target_rule_json clob,
  status varchar2(32 char) default 'queued' not null,
  scheduled_at timestamp(6) with time zone,
  sent_at timestamp(6) with time zone,
  created_by bigint,
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  check (channel in ('miniprogram', 'sms', 'email')),
  check (status in ('queued', 'sending', 'done', 'failed', 'canceled')),
  check (target_rule_json is json),
  check (ext_json is json),
  foreign key (notice_id) references campus.notice_item(id),
  foreign key (created_by) references campus.sys_user(id)
);

create index idx_notice_delivery_status on campus.notice_delivery(status, scheduled_at);

create table campus.notice_delivery_target (
  id bigint generated by default as identity primary key,
  delivery_id bigint not null,
  target_user_id bigint not null,
  status varchar2(32 char) default 'queued' not null,
  sent_at timestamp(6) with time zone,
  error_message clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  unique (delivery_id, target_user_id),
  check (status in ('queued', 'sent', 'failed', 'canceled')),
  foreign key (delivery_id) references campus.notice_delivery(id),
  foreign key (target_user_id) references campus.sys_user(id)
);

create index idx_notice_delivery_target_status on campus.notice_delivery_target(status, created_at);

create table campus.wf_definition (
  id bigint generated by default as identity primary key,
  wf_code varchar2(64 char) not null,
  wf_name varchar2(128 char) not null,
  business_type varchar2(64 char) not null,
  is_active number(1) default 1 not null,
  created_by bigint,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (wf_code),
  foreign key (created_by) references campus.sys_user(id),
  check (is_active in (0, 1)),
  check (is_deleted in (0, 1))
);

create table campus.wf_node (
  id bigint generated by default as identity primary key,
  wf_id bigint not null,
  seq_no number(10) not null,
  node_name varchar2(128 char) not null,
  approver_role_id bigint,
  approver_user_id bigint,
  sla_hours number(10),
  allow_reject number(1) default 1 not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (wf_id, seq_no),
  foreign key (wf_id) references campus.wf_definition(id),
  foreign key (approver_role_id) references campus.sys_role(id),
  foreign key (approver_user_id) references campus.sys_user(id),
  check (allow_reject in (0, 1)),
  check (is_deleted in (0, 1))
);

create table campus.wf_instance (
  id bigint generated by default as identity primary key,
  wf_id bigint not null,
  business_table varchar2(64 char) not null,
  business_id bigint not null,
  status varchar2(32 char) default 'running' not null,
  started_by bigint not null,
  started_at timestamp(6) with time zone default systimestamp not null,
  finished_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  check (status in ('running', 'approved', 'rejected', 'canceled')),
  foreign key (wf_id) references campus.wf_definition(id),
  foreign key (started_by) references campus.sys_user(id)
);

create index idx_wf_instance_biz on campus.wf_instance(business_table, business_id);
create index idx_wf_instance_status on campus.wf_instance(status, started_at);

create table campus.wf_task (
  id bigint generated by default as identity primary key,
  wf_instance_id bigint not null,
  wf_node_id bigint not null,
  assignee_user_id bigint,
  status varchar2(32 char) default 'pending' not null,
  due_at timestamp(6) with time zone,
  completed_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  check (status in ('pending', 'approved', 'rejected', 'canceled')),
  foreign key (wf_instance_id) references campus.wf_instance(id),
  foreign key (wf_node_id) references campus.wf_node(id),
  foreign key (assignee_user_id) references campus.sys_user(id)
);

create index idx_wf_task_status on campus.wf_task(status, due_at);

create table campus.wf_task_action (
  id bigint generated by default as identity primary key,
  wf_task_id bigint not null,
  actor_user_id bigint not null,
  action varchar2(32 char) not null,
  action_comment clob,
  action_at timestamp(6) with time zone default systimestamp not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  check (action in ('approve', 'reject', 'cancel', 'transfer')),
  foreign key (wf_task_id) references campus.wf_task(id),
  foreign key (actor_user_id) references campus.sys_user(id)
);

create table campus.affair_request (
  id bigint generated by default as identity primary key,
  requester_user_id bigint not null,
  request_type varchar2(32 char) not null,
  title varchar2(256 char),
  purpose varchar2(256 char) not null,
  remark clob,
  payload_json clob,
  status varchar2(32 char) default 'draft' not null,
  submitted_at timestamp(6) with time zone,
  closed_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  check (request_type in ('certificate', 'leave', 'stamp', 'budget', 'other')),
  check (status in ('draft', 'submitted', 'in_review', 'approved', 'rejected', 'canceled', 'closed')),
  check (payload_json is json),
  check (is_deleted in (0, 1)),
  foreign key (requester_user_id) references campus.sys_user(id)
);

create index idx_affair_request_requester on campus.affair_request(requester_user_id, created_at desc);
create index idx_affair_request_status on campus.affair_request(status, submitted_at desc);

create table campus.affair_request_attachment (
  id bigint generated by default as identity primary key,
  request_id bigint not null,
  file_id bigint not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (request_id, file_id),
  foreign key (request_id) references campus.affair_request(id),
  foreign key (file_id) references campus.file_object(id)
);

create table campus.cert_template (
  id bigint generated by default as identity primary key,
  template_code varchar2(64 char) not null,
  template_name varchar2(128 char) not null,
  file_id bigint not null,
  output_format varchar2(16 char) default 'pdf' not null,
  is_active number(1) default 1 not null,
  created_by bigint,
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (template_code),
  check (output_format in ('pdf')),
  check (is_active in (0, 1)),
  check (is_deleted in (0, 1)),
  check (ext_json is json),
  foreign key (file_id) references campus.file_object(id),
  foreign key (created_by) references campus.sys_user(id)
);

create table campus.cert_template_keyword (
  id bigint generated by default as identity primary key,
  template_id bigint not null,
  keyword_id bigint not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (template_id, keyword_id),
  foreign key (template_id) references campus.cert_template(id),
  foreign key (keyword_id) references campus.kb_keyword(id)
);

create index idx_cert_template_keyword_keyword on campus.cert_template_keyword(keyword_id, template_id);

create table campus.cert_application (
  id bigint generated by default as identity primary key,
  request_id bigint not null,
  template_id bigint not null,
  generated_pdf_file_id bigint,
  student_snapshot_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  unique (request_id),
  foreign key (request_id) references campus.affair_request(id),
  foreign key (template_id) references campus.cert_template(id),
  foreign key (generated_pdf_file_id) references campus.file_object(id),
  check (student_snapshot_json is json)
);

create table campus.cert_generated_file (
  id bigint generated by default as identity primary key,
  cert_app_id bigint not null,
  file_id bigint not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (cert_app_id, file_id),
  foreign key (cert_app_id) references campus.cert_application(id),
  foreign key (file_id) references campus.file_object(id)
);

create table campus.aca_program (
  id bigint generated by default as identity primary key,
  program_code varchar2(64 char) not null,
  major_name varchar2(128 char) not null,
  grade_year number(10) not null,
  version_name varchar2(64 char) not null,
  description clob,
  is_active number(1) default 1 not null,
  created_by bigint,
  ext_json clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (program_code),
  foreign key (created_by) references campus.sys_user(id),
  check (is_active in (0, 1)),
  check (is_deleted in (0, 1)),
  check (ext_json is json)
);

create index idx_aca_program_major_grade on campus.aca_program(major_name, grade_year, is_active);

create table campus.aca_program_module (
  id bigint generated by default as identity primary key,
  program_id bigint not null,
  module_code varchar2(64 char) not null,
  module_name varchar2(128 char) not null,
  module_type varchar2(32 char) not null,
  required_credits number(6, 2) not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (program_id, module_code),
  check (module_type in ('required', 'elective', 'general')),
  check (is_deleted in (0, 1)),
  foreign key (program_id) references campus.aca_program(id)
);

create table campus.aca_course (
  id bigint generated by default as identity primary key,
  course_code varchar2(64 char) not null,
  course_name varchar2(256 char) not null,
  credits number(5, 2) default 0 not null,
  course_type varchar2(32 char) default 'unknown' not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (course_code),
  check (course_type in ('required', 'elective', 'general', 'unknown')),
  check (is_deleted in (0, 1))
);

create index idx_aca_course_name on campus.aca_course(course_name);

create table campus.aca_term (
  id bigint generated by default as identity primary key,
  term_code varchar2(64 char) not null,
  term_name varchar2(128 char) not null,
  academic_year varchar2(32 char) not null,
  semester_no number(10) not null,
  start_date date,
  end_date date,
  is_current number(1) default 0 not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (term_code),
  check (semester_no in (1, 2, 3)),
  check (is_current in (0, 1)),
  check (is_deleted in (0, 1))
);

create index idx_aca_term_year_semester on campus.aca_term(academic_year, semester_no, is_current);

create table campus.aca_term_course (
  id bigint generated by default as identity primary key,
  term_id bigint not null,
  course_id bigint,
  teaching_class_code varchar2(64 char),
  course_code varchar2(64 char) not null,
  course_name varchar2(256 char) not null,
  teacher_name varchar2(128 char) not null,
  course_location varchar2(256 char),
  credits number(5, 2) default 0 not null,
  total_hours number(6, 2) default 0 not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  is_deleted number(1) default 0 not null,
  unique (term_id, teaching_class_code),
  foreign key (term_id) references campus.aca_term(id),
  foreign key (course_id) references campus.aca_course(id),
  check (credits >= 0),
  check (total_hours >= 0),
  check (is_deleted in (0, 1))
);

create index idx_aca_term_course_term_code on campus.aca_term_course(term_id, course_code);
create index idx_aca_term_course_course on campus.aca_term_course(course_id);

create table campus.aca_module_course (
  id bigint generated by default as identity primary key,
  module_id bigint not null,
  course_id bigint not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (module_id, course_id),
  foreign key (module_id) references campus.aca_program_module(id),
  foreign key (course_id) references campus.aca_course(id)
);

create table campus.aca_transcript (
  id bigint generated by default as identity primary key,
  student_user_id bigint not null,
  source_file_id bigint not null,
  parse_status varchar2(32 char) default 'pending' not null,
  parsed_at timestamp(6) with time zone,
  total_credits number(7, 2),
  gpa number(4, 2),
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  check (parse_status in ('pending', 'parsed', 'failed')),
  foreign key (student_user_id) references campus.sys_user(id),
  foreign key (source_file_id) references campus.file_object(id)
);

create index idx_aca_transcript_student on campus.aca_transcript(student_user_id, created_at desc);

create table campus.aca_transcript_item (
  id bigint generated by default as identity primary key,
  transcript_id bigint not null,
  term varchar2(32 char),
  course_code varchar2(64 char),
  course_name varchar2(256 char) not null,
  credits number(5, 2) default 0 not null,
  grade_text varchar2(32 char),
  grade_point number(4, 2),
  passed number(1) default 1 not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  foreign key (transcript_id) references campus.aca_transcript(id),
  check (passed in (0, 1))
);

create index idx_aca_transcript_item_transcript on campus.aca_transcript_item(transcript_id);

create table campus.aca_audit_report (
  id bigint generated by default as identity primary key,
  student_user_id bigint not null,
  program_id bigint not null,
  transcript_id bigint not null,
  status varchar2(32 char) default 'generated' not null,
  missing_module_count number(10) default 0 not null,
  generated_at timestamp(6) with time zone default systimestamp not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  check (status in ('generated', 'outdated')),
  foreign key (student_user_id) references campus.sys_user(id),
  foreign key (program_id) references campus.aca_program(id),
  foreign key (transcript_id) references campus.aca_transcript(id)
);

create index idx_aca_audit_report_student on campus.aca_audit_report(student_user_id, generated_at desc);

create table campus.aca_audit_missing (
  id bigint generated by default as identity primary key,
  report_id bigint not null,
  module_id bigint not null,
  missing_credits number(6, 2) not null,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (report_id, module_id),
  foreign key (report_id) references campus.aca_audit_report(id),
  foreign key (module_id) references campus.aca_program_module(id)
);

create table campus.aca_course_recommendation (
  id bigint generated by default as identity primary key,
  report_id bigint not null,
  module_id bigint not null,
  course_id bigint not null,
  recommendation_reason clob,
  created_at timestamp(6) with time zone default systimestamp not null,
  unique (report_id, course_id),
  foreign key (report_id) references campus.aca_audit_report(id),
  foreign key (module_id) references campus.aca_program_module(id),
  foreign key (course_id) references campus.aca_term_course(id)
);

create table campus.audit_import_job (
  id bigint generated by default as identity primary key,
  job_type varchar2(64 char) not null,
  source_file_id bigint not null,
  status varchar2(32 char) default 'running' not null,
  total_rows number(10),
  success_rows number(10),
  failed_rows number(10),
  error_message clob,
  result_json clob,
  started_by bigint,
  started_at timestamp(6) with time zone default systimestamp not null,
  finished_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default systimestamp not null,
  updated_at timestamp(6) with time zone default systimestamp not null,
  check (status in ('running', 'done', 'failed', 'canceled')),
  check (result_json is json),
  foreign key (source_file_id) references campus.file_object(id),
  foreign key (started_by) references campus.sys_user(id)
);

create index idx_audit_import_job_status on campus.audit_import_job(status, started_at);
