-- Backend bridge for the latest CAMPUS schema.
--
-- Purpose:
-- 1. Keep the current Spring Boot/JPA code working against the latest `campus.*` database.
-- 2. Materialize the legacy backend tables expected by the current application.
-- 3. Seed the legacy tables from the new normalized schema where a direct mapping exists.
--
-- Notes:
-- - This bridge is intentionally pragmatic: it favors running the backend now over a full Java-side rewrite.
-- - The sync is one-way bootstrap/import. New writes made by the current backend stay in the legacy bridge tables.
-- - Execute this after `db/kingbase_schema.sql`.

SET search_path TO campus;

-- Default bcrypt hash for demo password `123456`.
-- Used when the latest sample data carries placeholder hashes that cannot pass BCrypt validation.
-- Hash value generated on 2026-03-28 with BCrypt cost 12.

CREATE TABLE IF NOT EXISTS campus.user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    wechat_open_id VARCHAR(128),
    password_reset_required BOOLEAN NOT NULL DEFAULT FALSE,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP
);

CREATE TABLE IF NOT EXISTS campus.student_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student_no VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    major VARCHAR(64),
    grade VARCHAR(32),
    class_name VARCHAR(32),
    advisor_scope VARCHAR(64),
    degree_level VARCHAR(32),
    encrypted_id_card_no VARCHAR(128),
    encrypted_phone VARCHAR(128),
    email VARCHAR(128),
    graduated BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(64),
    major_changed_to VARCHAR(64),
    encrypted_native_place VARCHAR(128),
    encrypted_household_address VARCHAR(128),
    encrypted_supervisor VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS campus.knowledge_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    official_url VARCHAR(500),
    published BOOLEAN NOT NULL DEFAULT TRUE,
    source_file_name VARCHAR(255),
    audience_scope VARCHAR(64),
    updated_by VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS campus.party_progress_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student_id BIGINT NOT NULL,
    current_stage VARCHAR(64) NOT NULL,
    stage_start_date DATE NOT NULL,
    completed_actions VARCHAR(500),
    next_action VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS campus.notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(1000) NOT NULL,
    tag VARCHAR(100),
    target_grade VARCHAR(64),
    target_major VARCHAR(64),
    target_graduate_only BOOLEAN NOT NULL DEFAULT FALSE,
    publish_time TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS campus.certificate_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student_id BIGINT NOT NULL,
    certificate_type VARCHAR(100) NOT NULL,
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(500),
    generated_pdf_path VARCHAR(255),
    current_approver_role VARCHAR(32) NOT NULL DEFAULT 'COUNSELOR',
    approval_level INTEGER NOT NULL DEFAULT 1,
    withdrawal_deadline TIMESTAMP
);

CREATE TABLE IF NOT EXISTS campus.academic_warning_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student_id BIGINT NOT NULL,
    module_name VARCHAR(100) NOT NULL,
    required_credits INTEGER NOT NULL,
    earned_credits INTEGER NOT NULL,
    recommended_courses VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS campus.approval_action_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,
    operator_name VARCHAR(64) NOT NULL,
    operator_role VARCHAR(32) NOT NULL,
    action VARCHAR(32) NOT NULL,
    from_status VARCHAR(32) NOT NULL,
    to_status VARCHAR(32) NOT NULL,
    comment VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS campus.admin_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    operator_id BIGINT NOT NULL,
    operator_name VARCHAR(64) NOT NULL,
    operator_role VARCHAR(32) NOT NULL,
    module VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target VARCHAR(255) NOT NULL,
    result VARCHAR(32) NOT NULL,
    detail VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS campus.data_import_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    task_type VARCHAR(64) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_rows INTEGER NOT NULL DEFAULT 0,
    success_rows INTEGER NOT NULL DEFAULT 0,
    failed_rows INTEGER NOT NULL DEFAULT 0,
    owner_id BIGINT NOT NULL,
    owner_name VARCHAR(64) NOT NULL,
    error_summary VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS campus.student_work_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student_id BIGINT NOT NULL,
    student_name VARCHAR(64) NOT NULL,
    category VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    workload_score INTEGER NOT NULL,
    work_date DATE NOT NULL,
    recorder_name VARCHAR(64) NOT NULL,
    recorder_role VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS campus.student_portrait (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student_id BIGINT NOT NULL UNIQUE,
    honors VARCHAR(255),
    competitions VARCHAR(255),
    social_practice VARCHAR(255),
    research_experience VARCHAR(255),
    discipline_records VARCHAR(255),
    daily_performance VARCHAR(255),
    grade_rank INTEGER,
    major_rank INTEGER,
    updated_by VARCHAR(64),
    data_source VARCHAR(64),
    public_visible BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS campus.advisor_scope_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advisor_username VARCHAR(64) NOT NULL,
    advisor_name VARCHAR(64),
    grade VARCHAR(32),
    class_name VARCHAR(32),
    student_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_advisor_scope_binding_advisor
    ON campus.advisor_scope_binding (advisor_username, advisor_name);

CREATE INDEX IF NOT EXISTS idx_advisor_scope_binding_student
    ON campus.advisor_scope_binding (student_id);

CREATE TABLE IF NOT EXISTS campus.student_work_log_action_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    work_log_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,
    operator_name VARCHAR(64) NOT NULL,
    operator_role VARCHAR(32) NOT NULL,
    action VARCHAR(32) NOT NULL,
    detail VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS campus.knowledge_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    knowledge_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(128),
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    uploaded_by VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS campus.data_import_error_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    task_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,
    field_name VARCHAR(64) NOT NULL,
    error_message VARCHAR(500) NOT NULL,
    raw_value VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS campus.student_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student_id BIGINT NOT NULL,
    from_status VARCHAR(64),
    to_status VARCHAR(64) NOT NULL,
    changed_to_major VARCHAR(64),
    reason VARCHAR(1000),
    changed_by VARCHAR(64) NOT NULL,
    changed_by_role VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS campus.platform_file_upload_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    biz_type VARCHAR(64) NOT NULL,
    biz_id BIGINT,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(128),
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    uploaded_by_id BIGINT NOT NULL,
    uploaded_by VARCHAR(64) NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS campus.login_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT,
    username VARCHAR(64) NOT NULL,
    role VARCHAR(32),
    action VARCHAR(32) NOT NULL,
    result VARCHAR(32) NOT NULL,
    detail VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS campus.revoked_token_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    username VARCHAR(64) NOT NULL,
    revoked_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS campus.user_session_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    username VARCHAR(64) NOT NULL,
    role VARCHAR(32) NOT NULL,
    login_at TIMESTAMP NOT NULL,
    logout_at TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS campus.platform_system_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    setting_key VARCHAR(128) NOT NULL UNIQUE,
    setting_value VARCHAR(500) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS campus.platform_notification_send_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(200) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_description VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    recipient_count INTEGER NOT NULL,
    triggered_by VARCHAR(64) NOT NULL,
    sent_at TIMESTAMP NOT NULL,
    extension_channels VARCHAR(255)
);

INSERT INTO campus.user_account (
    id,
    created_at,
    updated_at,
    username,
    password_hash,
    role,
    enabled,
    wechat_open_id,
    password_reset_required,
    failed_login_attempts,
    locked_until
)
SELECT
    u.id,
    COALESCE(u.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(u.updated_at::timestamp, CURRENT_TIMESTAMP),
    u.student_no,
    CASE
        WHEN auth.password_hash ~ '^\$2[aby]\$[0-9]{2}\$.{53}$' THEN auth.password_hash
        ELSE '$2b$12$fPjHdxqUa..LtwF.XCknguSXwVR56f0chfM61/jDh1zDU/w7u.DRq'
    END,
    CASE lower(r.role_code)
        WHEN 'student' THEN 'STUDENT'
        WHEN 'cadre' THEN 'LEAGUE_SECRETARY'
        WHEN 'teacher_admin' THEN 'COLLEGE_ADMIN'
        WHEN 'college_leader' THEN 'SUPER_ADMIN'
        ELSE 'STUDENT'
    END,
    u.status = 'active',
    wx.wechat_openid,
    FALSE,
    0,
    NULL
FROM campus.sys_user u
LEFT JOIN campus.sys_user_role ur ON ur.user_id = u.id
LEFT JOIN campus.sys_role r ON r.id = ur.role_id
LEFT JOIN campus.sys_user_auth auth
    ON auth.student_no = u.student_no
   AND auth.login_method = 'password'
   AND auth.is_deleted = 0
LEFT JOIN campus.sys_user_auth wx
    ON wx.student_no = u.student_no
   AND wx.login_method = 'wechat'
   AND wx.is_deleted = 0
WHERE u.is_deleted = 0
  AND NOT EXISTS (
      SELECT 1 FROM campus.user_account existing WHERE existing.id = u.id
  );

INSERT INTO campus.advisor_scope_binding (
    advisor_username,
    advisor_name,
    grade,
    class_name,
    student_id,
    created_at,
    updated_at
)
SELECT
    advisor.student_no,
    advisor.full_name,
    CASE
        WHEN ext.grade_year IS NULL THEN NULL
        ELSE ext.grade_year::varchar || '级'
    END,
    LEFT(ext.class_name, 32),
    stu.id,
    COALESCE(ext.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(ext.updated_at::timestamp, CURRENT_TIMESTAMP)
FROM campus.sys_student_ext ext
JOIN campus.sys_user stu ON stu.student_no = ext.student_no AND stu.is_deleted = 0
LEFT JOIN campus.sys_user advisor
    ON advisor.full_name = COALESCE((ext.ext_json::json) ->> 'advisor', (ext.ext_json::json) ->> 'advisorName')
   AND advisor.is_deleted = 0
WHERE COALESCE((ext.ext_json::json) ->> 'advisor', (ext.ext_json::json) ->> 'advisorName') IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM campus.advisor_scope_binding existing
      WHERE existing.student_id = stu.id
        AND existing.advisor_username = advisor.student_no
        AND COALESCE(existing.class_name, '') = COALESCE(LEFT(ext.class_name, 32), '')
  );

INSERT INTO campus.student_profile (
    id,
    created_at,
    updated_at,
    student_no,
    name,
    major,
    grade,
    class_name,
    advisor_scope,
    degree_level,
    encrypted_id_card_no,
    encrypted_phone,
    email,
    graduated,
    status,
    major_changed_to,
    encrypted_native_place,
    encrypted_household_address,
    encrypted_supervisor
)
SELECT
    u.id,
    COALESCE(ext.created_at::timestamp, u.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(ext.updated_at::timestamp, u.updated_at::timestamp, CURRENT_TIMESTAMP),
    u.student_no,
    u.full_name,
    LEFT(ext.major_name, 64),
    CASE
        WHEN ext.grade_year IS NULL THEN NULL
        ELSE ext.grade_year::varchar || '级'
    END,
    LEFT(ext.class_name, 32),
    NULL,
    CASE
        WHEN ext.ext_json IS NOT NULL AND ext.ext_json::text ILIKE '%硕%' THEN '硕士'
        WHEN ext.ext_json IS NOT NULL AND ext.ext_json::text ILIKE '%博%' THEN '博士'
        ELSE '本科'
    END,
    ext.id_card_hash,
    ext.phone_hash,
    NULL,
    lower(COALESCE(ext.party_status, '')) LIKE '%毕业%',
    CASE
        WHEN u.status = 'disabled' THEN 'DISABLED'
        WHEN lower(COALESCE(ext.party_status, '')) LIKE '%毕业%' THEN 'GRADUATED'
        ELSE 'ACTIVE'
    END,
    NULL,
    NULL,
    ext.home_address_hash,
    NULL
FROM campus.sys_user u
LEFT JOIN campus.sys_student_ext ext ON ext.student_no = u.student_no
WHERE u.is_deleted = 0
  AND NOT EXISTS (
      SELECT 1 FROM campus.student_profile existing WHERE existing.id = u.id
  );

INSERT INTO campus.knowledge_document (
    id,
    created_at,
    updated_at,
    title,
    category,
    content,
    official_url,
    published,
    source_file_name,
    audience_scope,
    updated_by
)
SELECT
    p.id,
    COALESCE(p.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(p.updated_at::timestamp, CURRENT_TIMESTAMP),
    LEFT(p.title, 200),
    CASE
        WHEN p.source_type = 'import' THEN '导入资料'
        WHEN p.source_type = 'crawl' THEN '采集资料'
        ELSE '政策知识'
    END,
    COALESCE(NULLIF(p.content, ''), NULLIF(p.summary, ''), p.title),
    p.source_url,
    p.is_published = 1,
    LEFT(f.original_name, 255),
    NULL,
    LEFT(creator.full_name, 64)
FROM campus.kb_policy p
LEFT JOIN campus.file_object f ON f.id = p.attachment_file_id
LEFT JOIN campus.sys_user creator ON creator.id = p.created_by
WHERE p.is_deleted = 0
  AND NOT EXISTS (
      SELECT 1 FROM campus.knowledge_document existing WHERE existing.id = p.id
  );

INSERT INTO campus.knowledge_attachment (
    id,
    created_at,
    updated_at,
    knowledge_id,
    file_name,
    content_type,
    file_size,
    storage_path,
    uploaded_by
)
SELECT
    f.id,
    COALESCE(f.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(f.updated_at::timestamp, CURRENT_TIMESTAMP),
    p.id,
    LEFT(f.original_name, 255),
    f.mime_type,
    f.size_bytes,
    LEFT(f.storage_path, 500),
    COALESCE(u.full_name, u.student_no, 'system')
FROM campus.kb_policy p
JOIN campus.file_object f ON f.id = p.attachment_file_id
LEFT JOIN campus.sys_user u ON u.id = f.uploaded_by
WHERE p.is_deleted = 0
  AND f.is_deleted = 0
  AND NOT EXISTS (
      SELECT 1 FROM campus.knowledge_attachment existing WHERE existing.id = f.id
  );

INSERT INTO campus.notice (
    id,
    created_at,
    updated_at,
    title,
    summary,
    tag,
    target_grade,
    target_major,
    target_graduate_only,
    publish_time
)
SELECT
    n.id,
    COALESCE(n.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(n.updated_at::timestamp, CURRENT_TIMESTAMP),
    LEFT(n.title, 200),
    LEFT(COALESCE(n.content, n.title), 1000),
    LEFT((
        SELECT string_agg(tag.tag_name, ',' ORDER BY tag.tag_name)
        FROM campus.notice_item_tag nit
        JOIN campus.notice_tag_dict tag ON tag.id = nit.tag_id
        WHERE nit.notice_id = n.id
    ), 100),
    NULL,
    NULL,
    FALSE,
    COALESCE(n.publish_at::timestamp, n.created_at::timestamp, CURRENT_TIMESTAMP)
FROM campus.notice_item n
WHERE n.is_deleted = 0
  AND NOT EXISTS (
      SELECT 1 FROM campus.notice existing WHERE existing.id = n.id
  );

INSERT INTO campus.party_progress_record (
    id,
    created_at,
    updated_at,
    student_id,
    current_stage,
    stage_start_date,
    completed_actions,
    next_action
)
SELECT
    p.id,
    COALESCE(p.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(p.updated_at::timestamp, CURRENT_TIMESTAMP),
    p.student_user_id,
    LEFT(COALESCE(node.node_name, flow.flow_name, p.status), 64),
    COALESCE(p.started_at::date, p.created_at::date, CURRENT_DATE),
    LEFT('status=' || p.status, 500),
    LEFT(COALESCE('下一截止时间: ' || to_char(p.next_deadline_at::timestamp, 'YYYY-MM-DD HH24:MI'), flow.flow_name), 500)
FROM campus.party_student_progress p
LEFT JOIN campus.party_flow_node node ON node.id = p.current_node_id
LEFT JOIN campus.party_flow flow ON flow.id = p.flow_id
WHERE p.is_deleted = 0
  AND NOT EXISTS (
      SELECT 1 FROM campus.party_progress_record existing WHERE existing.id = p.id
  );

INSERT INTO campus.certificate_request (
    id,
    created_at,
    updated_at,
    student_id,
    certificate_type,
    status,
    reason,
    generated_pdf_path,
    current_approver_role,
    approval_level,
    withdrawal_deadline
)
SELECT
    ca.id,
    COALESCE(ca.created_at::timestamp, ar.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(ca.updated_at::timestamp, ar.updated_at::timestamp, CURRENT_TIMESTAMP),
    ar.requester_user_id,
    LEFT(COALESCE(ct.template_name, ar.title, ar.request_type), 100),
    CASE ar.status
        WHEN 'approved' THEN 'APPROVED'
        WHEN 'rejected' THEN 'REJECTED'
        WHEN 'canceled' THEN 'WITHDRAWN'
        WHEN 'closed' THEN 'APPROVED'
        WHEN 'in_review' THEN 'COUNSELOR_APPROVED'
        ELSE 'PENDING'
    END,
    LEFT(ar.purpose, 500),
    gf.storage_path,
    CASE ar.status
        WHEN 'submitted' THEN 'COUNSELOR'
        WHEN 'in_review' THEN 'COLLEGE_ADMIN'
        ELSE 'ARCHIVED'
    END,
    CASE ar.status
        WHEN 'in_review' THEN 2
        WHEN 'approved' THEN 3
        WHEN 'rejected' THEN 3
        WHEN 'canceled' THEN 3
        WHEN 'closed' THEN 3
        ELSE 1
    END,
    CASE
        WHEN ar.status IN ('submitted', 'in_review') THEN COALESCE(ar.submitted_at::timestamp, ar.created_at::timestamp) + INTERVAL '2 day'
        ELSE NULL
    END
FROM campus.cert_application ca
JOIN campus.affair_request ar ON ar.id = ca.request_id
LEFT JOIN campus.cert_template ct ON ct.id = ca.template_id
LEFT JOIN campus.file_object gf ON gf.id = ca.generated_pdf_file_id
WHERE NOT EXISTS (
    SELECT 1 FROM campus.certificate_request existing WHERE existing.id = ca.id
);

INSERT INTO campus.approval_action_log (
    id,
    created_at,
    updated_at,
    request_id,
    operator_id,
    operator_name,
    operator_role,
    action,
    from_status,
    to_status,
    comment
)
SELECT
    action.id,
    COALESCE(action.created_at::timestamp, action.action_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(action.created_at::timestamp, action.action_at::timestamp, CURRENT_TIMESTAMP),
    cert.id,
    actor.id,
    actor.full_name,
    CASE lower(role.role_code)
        WHEN 'student' THEN 'STUDENT'
        WHEN 'cadre' THEN 'LEAGUE_SECRETARY'
        WHEN 'teacher_admin' THEN 'COUNSELOR'
        WHEN 'college_leader' THEN 'SUPER_ADMIN'
        ELSE 'ASSISTANT'
    END,
    upper(action.action),
    CASE
        WHEN wt.seq_no = 1 THEN 'PENDING'
        ELSE 'COUNSELOR_APPROVED'
    END,
    CASE lower(action.action)
        WHEN 'approve' THEN CASE WHEN wt.seq_no = 1 THEN 'COUNSELOR_APPROVED' ELSE 'APPROVED' END
        WHEN 'reject' THEN 'REJECTED'
        ELSE upper(action.action)
    END,
    LEFT(action.action_comment, 500)
FROM campus.wf_task_action action
JOIN campus.wf_task task ON task.id = action.wf_task_id
JOIN campus.wf_node wt ON wt.id = task.wf_node_id
JOIN campus.wf_instance inst ON inst.id = task.wf_instance_id
JOIN campus.cert_application cert ON cert.request_id = inst.business_id
LEFT JOIN campus.sys_user actor ON actor.id = action.actor_user_id
LEFT JOIN campus.sys_user_role ur ON ur.user_id = actor.id
LEFT JOIN campus.sys_role role ON role.id = ur.role_id
WHERE inst.business_table = 'campus.affair_request'
  AND NOT EXISTS (
      SELECT 1 FROM campus.approval_action_log existing WHERE existing.id = action.id
  );

INSERT INTO campus.academic_warning_record (
    id,
    created_at,
    updated_at,
    student_id,
    module_name,
    required_credits,
    earned_credits,
    recommended_courses
)
SELECT
    missing.id,
    COALESCE(report.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(report.updated_at::timestamp, CURRENT_TIMESTAMP),
    report.student_user_id,
    LEFT(module.module_name, 100),
    COALESCE(module.required_credits, 0)::integer,
    GREATEST(COALESCE(module.required_credits, 0) - COALESCE(missing.missing_credits, 0), 0)::integer,
    LEFT((
        SELECT string_agg(tc.course_name, '、' ORDER BY tc.course_name)
        FROM campus.aca_course_recommendation rec
        JOIN campus.aca_term_course tc ON tc.id = rec.course_id
        WHERE rec.report_id = report.id
          AND rec.module_id = module.id
    ), 500)
FROM campus.aca_audit_missing missing
JOIN campus.aca_audit_report report ON report.id = missing.report_id
JOIN campus.aca_program_module module ON module.id = missing.module_id
WHERE NOT EXISTS (
    SELECT 1 FROM campus.academic_warning_record existing WHERE existing.id = missing.id
);

INSERT INTO campus.data_import_task (
    id,
    created_at,
    updated_at,
    task_type,
    file_name,
    status,
    total_rows,
    success_rows,
    failed_rows,
    owner_id,
    owner_name,
    error_summary
)
SELECT
    job.id,
    COALESCE(job.created_at::timestamp, job.started_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(job.updated_at::timestamp, job.finished_at::timestamp, CURRENT_TIMESTAMP),
    job.job_type,
    LEFT(file.original_name, 255),
    CASE job.status
        WHEN 'running' THEN 'RUNNING'
        WHEN 'done' THEN CASE WHEN COALESCE(job.failed_rows, 0) > 0 THEN 'PARTIAL_SUCCESS' ELSE 'SUCCESS' END
        WHEN 'failed' THEN 'FAILED'
        ELSE 'CREATED'
    END,
    COALESCE(job.total_rows, 0)::integer,
    COALESCE(job.success_rows, 0)::integer,
    COALESCE(job.failed_rows, 0)::integer,
    COALESCE(starter.id, 0),
    COALESCE(starter.full_name, starter.student_no, 'system'),
    LEFT(job.error_message, 1000)
FROM campus.audit_import_job job
LEFT JOIN campus.file_object file ON file.id = job.source_file_id
LEFT JOIN campus.sys_user starter ON starter.id = job.started_by
WHERE NOT EXISTS (
    SELECT 1 FROM campus.data_import_task existing WHERE existing.id = job.id
);

INSERT INTO campus.admin_operation_log (
    id,
    created_at,
    updated_at,
    operator_id,
    operator_name,
    operator_role,
    module,
    action,
    target,
    result,
    detail
)
SELECT
    log.id,
    COALESCE(log.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(log.created_at::timestamp, CURRENT_TIMESTAMP),
    COALESCE(op.id, 0),
    COALESCE(op.full_name, op.student_no, 'system'),
    CASE lower(role.role_code)
        WHEN 'student' THEN 'STUDENT'
        WHEN 'cadre' THEN 'LEAGUE_SECRETARY'
        WHEN 'teacher_admin' THEN 'COUNSELOR'
        WHEN 'college_leader' THEN 'SUPER_ADMIN'
        ELSE 'ASSISTANT'
    END,
    upper(log.module_code),
    upper(log.operation_type),
    LEFT(COALESCE(log.business_type, log.module_code) || '#' || COALESCE(log.business_id::varchar, '0'), 255),
    CASE lower(log.result_status)
        WHEN 'success' THEN 'SUCCESS'
        WHEN 'partial' THEN 'SUCCESS'
        ELSE 'FAILED'
    END,
    LEFT(COALESCE(log.operation_desc, log.error_message, ''), 1000)
FROM campus.sys_operation_log log
LEFT JOIN campus.sys_user op ON op.id = log.operator_user_id
LEFT JOIN campus.sys_user_role ur ON ur.user_id = op.id
LEFT JOIN campus.sys_role role ON role.id = ur.role_id
WHERE NOT EXISTS (
    SELECT 1 FROM campus.admin_operation_log existing WHERE existing.id = log.id
);

INSERT INTO campus.platform_notification_send_record (
    title,
    channel,
    target_type,
    target_description,
    status,
    recipient_count,
    triggered_by,
    sent_at,
    extension_channels
)
SELECT
    n.title,
    'IN_APP',
    'ALL',
    '来自最新 notice_item 导入',
    'SENT',
    0,
    'system',
    COALESCE(n.publish_at::timestamp, n.created_at::timestamp, CURRENT_TIMESTAMP),
    'EMAIL,WECHAT'
FROM campus.notice_item n
WHERE n.is_deleted = 0
  AND NOT EXISTS (
      SELECT 1
      FROM campus.platform_notification_send_record existing
      WHERE existing.title = n.title
        AND existing.sent_at = COALESCE(n.publish_at::timestamp, n.created_at::timestamp, CURRENT_TIMESTAMP)
  );
