#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue May 19 21:41:27 CST 2026
maven-metadata-aliyunmaven.xml.lastUpdated=1779198087022
maven-metadata-central.xml.lastUpdated=1779198087021
maven-metadata-huaweicloud.xml.lastUpdated=1779198087022
