create table aca_program (
  id bigint generated by default as identity primary key,
  program_code VARCHAR(64) not null,
  major_name VARCHAR(128) not null,
  grade_year INTEGER not null,
  version_name VARCHAR(64) not null,
  description TEXT,
  is_active INTEGER default 1 not null,
  created_by bigint,
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (program_code),
  foreign key (created_by) references user_account(id),
  check (is_active in (0, 1)),
  check (is_deleted in (0, 1))
);

create index idx_aca_program_major_grade on aca_program(major_name, grade_year, is_active);

create table aca_program_module (
  id bigint generated by default as identity primary key,
  program_id bigint not null,
  module_code VARCHAR(64) not null,
  module_name VARCHAR(128) not null,
  module_type VARCHAR(32) not null,
  required_credits DECIMAL(6, 2) not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (program_id, module_code),
  check (module_type in ('required', 'elective', 'general')),
  check (is_deleted in (0, 1)),
  foreign key (program_id) references aca_program(id)
);

create table aca_course (
  id bigint generated by default as identity primary key,
  course_code VARCHAR(64) not null,
  course_name VARCHAR(256) not null,
  credits DECIMAL(5, 2) default 0 not null,
  course_type VARCHAR(32) default 'unknown' not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (course_code),
  check (course_type in ('required', 'elective', 'general', 'unknown')),
  check (is_deleted in (0, 1))
);

create index idx_aca_course_name on aca_course(course_name);

create table aca_term (
  id bigint generated by default as identity primary key,
  term_code VARCHAR(64) not null,
  term_name VARCHAR(128) not null,
  academic_year VARCHAR(32) not null,
  semester_no INTEGER not null,
  start_date date,
  end_date date,
  is_current INTEGER default 0 not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (term_code),
  check (semester_no in (1, 2, 3)),
  check (is_current in (0, 1)),
  check (is_deleted in (0, 1))
);

create index idx_aca_term_year_semester on aca_term(academic_year, semester_no, is_current);

create table aca_term_course (
  id bigint generated by default as identity primary key,
  term_id bigint not null,
  course_id bigint,
  teaching_class_code VARCHAR(64),
  course_code VARCHAR(64) not null,
  course_name VARCHAR(256) not null,
  teacher_name VARCHAR(128) not null,
  course_location VARCHAR(256),
  credits DECIMAL(5, 2) default 0 not null,
  total_hours INTEGER default 0 not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (term_id, teaching_class_code),
  foreign key (term_id) references aca_term(id),
  foreign key (course_id) references aca_course(id),
  check (credits >= 0),
  check (total_hours >= 0),
  check (is_deleted in (0, 1))
);

create index idx_aca_term_course_term_code on aca_term_course(term_id, course_code);
create index idx_aca_term_course_course on aca_term_course(course_id);

create table aca_module_course (
  id bigint generated by default as identity primary key,
  module_id bigint not null,
  course_id bigint not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (module_id, course_id),
  foreign key (module_id) references aca_program_module(id),
  foreign key (course_id) references aca_course(id)
);

create table aca_transcript (
  id bigint generated by default as identity primary key,
  student_user_id bigint not null,
  source_file_id bigint not null,
  parse_status VARCHAR(32) default 'pending' not null,
  parsed_at timestamp(6) with time zone,
  total_credits DECIMAL(7, 2),
  gpa DECIMAL(4, 2),
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  check (parse_status in ('pending', 'parsed', 'failed')),
  foreign key (student_user_id) references user_account(id),
  foreign key (source_file_id) references platform_file_upload_record(id)
);

create index idx_aca_transcript_student on aca_transcript(student_user_id, created_at desc);

create table aca_transcript_item (
  id bigint generated by default as identity primary key,
  transcript_id bigint not null,
  term VARCHAR(32),
  course_code VARCHAR(64),
  course_name VARCHAR(256) not null,
  credits DECIMAL(5, 2) default 0 not null,
  grade_text VARCHAR(32),
  grade_point DECIMAL(4, 2),
  passed INTEGER default 1 not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  foreign key (transcript_id) references aca_transcript(id),
  check (passed in (0, 1))
);

create index idx_aca_transcript_item_transcript on aca_transcript_item(transcript_id);

create table aca_audit_report (
  id bigint generated by default as identity primary key,
  student_user_id bigint not null,
  program_id bigint not null,
  transcript_id bigint not null,
  status VARCHAR(32) default 'generated' not null,
  missing_module_count INTEGER default 0 not null,
  generated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  check (status in ('generated', 'outdated')),
  foreign key (student_user_id) references user_account(id),
  foreign key (program_id) references aca_program(id),
  foreign key (transcript_id) references aca_transcript(id)
);

create index idx_aca_audit_report_student on aca_audit_report(student_user_id, generated_at desc);

create table aca_audit_missing (
  id bigint generated by default as identity primary key,
  report_id bigint not null,
  module_id bigint not null,
  missing_credits DECIMAL(6, 2) not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (report_id, module_id),
  foreign key (report_id) references aca_audit_report(id),
  foreign key (module_id) references aca_program_module(id)
);

create table aca_course_recommendation (
  id bigint generated by default as identity primary key,
  report_id bigint not null,
  module_id bigint not null,
  course_id bigint not null,
  recommendation_reason TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (report_id, course_id),
  foreign key (report_id) references aca_audit_report(id),
  foreign key (module_id) references aca_program_module(id),
  foreign key (course_id) references aca_term_course(id)
);
