create table wf_instance (
  id bigint generated by default as identity primary key,
  wf_id bigint not null,
  business_table VARCHAR(64) not null,
  business_id bigint not null,
  status VARCHAR(32) default 'running' not null,
  started_by bigint not null,
  started_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  finished_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  check (status in ('running', 'approved', 'rejected', 'canceled')),
  foreign key (wf_id) references wf_definition(id),
  foreign key (started_by) references user_account(id)
);

create index idx_wf_instance_biz on wf_instance(business_table, business_id);
create index idx_wf_instance_status on wf_instance(status, started_at);

create table wf_task (
  id bigint generated by default as identity primary key,
  wf_instance_id bigint not null,
  wf_node_id bigint not null,
  assignee_user_id bigint,
  status VARCHAR(32) default 'pending' not null,
  due_at timestamp(6) with time zone,
  completed_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  check (status in ('pending', 'approved', 'rejected', 'canceled')),
  foreign key (wf_instance_id) references wf_instance(id),
  foreign key (wf_node_id) references wf_node(id),
  foreign key (assignee_user_id) references user_account(id)
);

create index idx_wf_task_status on wf_task(status, due_at);

create table wf_task_action (
  id bigint generated by default as identity primary key,
  wf_task_id bigint not null,
  actor_user_id bigint not null,
  action VARCHAR(32) not null,
  action_comment TEXT,
  action_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  check (action in ('approve', 'reject', 'cancel', 'transfer')),
  foreign key (wf_task_id) references wf_task(id),
  foreign key (actor_user_id) references user_account(id)
);

create table affair_request (
  id bigint generated by default as identity primary key,
  requester_user_id bigint not null,
  request_type VARCHAR(32) not null,
  title VARCHAR(256),
  purpose VARCHAR(256) not null,
  remark TEXT,
  payload_json TEXT,
  status VARCHAR(32) default 'draft' not null,
  submitted_at timestamp(6) with time zone,
  closed_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  check (request_type in ('certificate', 'leave', 'stamp', 'budget', 'other')),
  check (status in ('draft', 'submitted', 'in_review', 'approved', 'rejected', 'canceled', 'closed')),
  check (is_deleted in (0, 1)),
  foreign key (requester_user_id) references user_account(id)
);

create index idx_affair_request_requester on affair_request(requester_user_id, created_at desc);
create index idx_affair_request_status on affair_request(status, submitted_at desc);

create table cert_template (
  id bigint generated by default as identity primary key,
  template_code VARCHAR(64) not null,
  template_name VARCHAR(128) not null,
  file_id bigint not null,
  output_format VARCHAR(16) default 'pdf' not null,
  is_active INTEGER default 1 not null,
  created_by bigint,
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (template_code),
  check (output_format in ('pdf')),
  check (is_active in (0, 1)),
  check (is_deleted in (0, 1)),
  
  foreign key (file_id) references platform_file_upload_record(id),
  foreign key (created_by) references user_account(id)
);

create table cert_template_keyword (
  id bigint generated by default as identity primary key,
  template_id bigint not null,
  keyword_id bigint not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (template_id, keyword_id),
  foreign key (template_id) references cert_template(id)
);

create index idx_cert_template_keyword_keyword on cert_template_keyword(keyword_id, template_id);

create table cert_application (
  id bigint generated by default as identity primary key,
  request_id bigint not null,
  template_id bigint not null,
  generated_pdf_file_id bigint,
  student_snapshot_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (request_id),
  foreign key (request_id) references affair_request(id),
  foreign key (template_id) references cert_template(id),
  foreign key (generated_pdf_file_id) references platform_file_upload_record(id)
);

create table cert_generated_file (
  id bigint generated by default as identity primary key,
  cert_app_id bigint not null,
  file_id bigint not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (cert_app_id, file_id),
  foreign key (cert_app_id) references cert_application(id),
  foreign key (file_id) references platform_file_upload_record(id)
);
