create table audit_import_job (
  id bigint generated by default as identity primary key,
  job_type VARCHAR(64) not null,
  source_file_id bigint not null,
  status VARCHAR(32) default 'running' not null,
  total_rows INTEGER,
  success_rows INTEGER,
  failed_rows INTEGER,
  error_message TEXT,
  result_json TEXT,
  started_by bigint,
  started_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  finished_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  check (status in ('running', 'done', 'failed', 'canceled')),
  foreign key (source_file_id) references platform_file_upload_record(id),
  foreign key (started_by) references user_account(id)
);

create index idx_audit_import_job_status on audit_import_job(status, started_at);
