create table sys_role (
  id bigint generated by default as identity primary key,
  role_code VARCHAR(64) not null,
  role_name VARCHAR(128) not null,
  permissions TEXT,
  is_active INTEGER default 1 not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (role_code),
  check (is_active in (0, 1)),
  check (is_deleted in (0, 1))
);

insert into sys_role (role_code, role_name) values 
  ('student', '普通学生'),
  ('cadre', '班团骨干'),
  ('teacher_admin', '管理老师'),
  ('college_leader', '学院领导')
on conflict (role_code) do nothing;

create table sys_user (
  id bigint generated by default as identity primary key,
  student_no VARCHAR(32) not null,
  full_name VARCHAR(64) not null,
  status VARCHAR(32) default 'active' not null,
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (student_no),
  check (status in ('active', 'disabled')),
  check (is_deleted in (0, 1))
);

create table sys_user_role (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  role_id bigint not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (user_id, role_id),
  foreign key (user_id) references sys_user(id),
  foreign key (role_id) references sys_role(id)
);

create table sys_user_auth (
  id bigint generated by default as identity primary key,
  student_no VARCHAR(32) not null,
  login_method VARCHAR(32) not null,
  wechat_openid VARCHAR(64),
  password_hash VARCHAR(255),
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (student_no, login_method),
  unique (wechat_openid),
  foreign key (student_no) references sys_user(student_no),
  check (login_method in ('wechat', 'password')),
  check (
    (login_method = 'wechat' and wechat_openid is not null and password_hash is null)
    or
    (login_method = 'password' and password_hash is not null and wechat_openid is null)
  ),
  check (is_deleted in (0, 1))
);

create table sys_student_ext (
  student_no VARCHAR(32) primary key,
  major_name VARCHAR(128) not null,
  grade_year INTEGER not null,
  class_name VARCHAR(128) not null,
  political_status VARCHAR(64) not null,
  party_status VARCHAR(64) not null,
  id_card_cipher BYTEA,
  id_card_hash VARCHAR(64),
  home_address_cipher BYTEA,
  home_address_hash VARCHAR(64),
  phone_cipher BYTEA,
  phone_hash VARCHAR(64),
  gpa DECIMAL(4, 2),
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  foreign key (student_no) references sys_user(student_no),
  check (is_deleted in (0, 1))
);

create table sys_operation_log (
  id bigint generated by default as identity primary key,
  module_code VARCHAR(64) not null,
  business_type VARCHAR(64),
  business_id bigint,
  operation_type VARCHAR(64) not null,
  operation_desc TEXT,
  operator_user_id bigint,
  trace_id VARCHAR(128),
  request_uri VARCHAR(512),
  request_method VARCHAR(16),
  request_ip VARCHAR(64),
  user_agent VARCHAR(512),
  log_level VARCHAR(16) default 'info' not null,
  result_status VARCHAR(16) default 'success' not null,
  error_message TEXT,
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  foreign key (operator_user_id) references sys_user(id),
  check (log_level in ('info', 'warn', 'error', 'audit')),
  check (result_status in ('success', 'fail', 'partial'))
);

create index idx_sys_operation_log_user on sys_operation_log(operator_user_id, created_at desc);
create index idx_sys_operation_log_biz on sys_operation_log(module_code, business_type, business_id);
create index idx_sys_operation_log_trace on sys_operation_log(trace_id);

create table file_object (
  id bigint generated by default as identity primary key,
  purpose VARCHAR(64) not null,
  original_name VARCHAR(256) not null,
  mime_type VARCHAR(128),
  size_bytes bigint not null,
  sha256 VARCHAR(64),
  storage_provider VARCHAR(64) not null,
  storage_path VARCHAR(512) not null,
  uploaded_by bigint,
  uploaded_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  foreign key (uploaded_by) references sys_user(id),
  check (is_deleted in (0, 1))
);

create index idx_file_object_purpose on file_object(purpose);
create index idx_file_object_sha256 on file_object(sha256);

create table kb_policy (
  id bigint generated by default as identity primary key,
  title VARCHAR(256) not null,
  summary TEXT,
  content TEXT,
  source_type VARCHAR(32) default 'manual' not null,
  source_url VARCHAR(512),
  attachment_file_id bigint,
  is_published INTEGER default 1 not null,
  published_at timestamp(6) with time zone,
  created_by bigint,
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  check (source_type in ('manual', 'crawl', 'import')),
  check (is_published in (0, 1)),
  check (is_deleted in (0, 1)),
  
  foreign key (attachment_file_id) references file_object(id),
  foreign key (created_by) references sys_user(id)
);

create index idx_kb_policy_published on kb_policy(is_published, published_at);

create table kb_faq (
  id bigint generated by default as identity primary key,
  question VARCHAR(512) not null,
  answer TEXT not null,
  source_policy_id bigint,
  is_published INTEGER default 1 not null,
  created_by bigint,
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  foreign key (source_policy_id) references kb_policy(id),
  foreign key (created_by) references sys_user(id),
  check (is_published in (0, 1)),
  check (is_deleted in (0, 1))
);

create index idx_kb_faq_published on kb_faq(is_published, created_at);

create table kb_keyword (
  id bigint generated by default as identity primary key,
  keyword VARCHAR(64) not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (keyword)
);

create table kb_policy_keyword (
  id bigint generated by default as identity primary key,
  policy_id bigint not null,
  keyword_id bigint not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (policy_id, keyword_id),
  foreign key (policy_id) references kb_policy(id),
  foreign key (keyword_id) references kb_keyword(id)
);

create table kb_faq_keyword (
  id bigint generated by default as identity primary key,
  faq_id bigint not null,
  keyword_id bigint not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (faq_id, keyword_id),
  foreign key (faq_id) references kb_faq(id),
  foreign key (keyword_id) references kb_keyword(id)
);

create table kb_keyword_search_history (
  id bigint generated by default as identity primary key,
  search_user_id bigint,
  keyword_id bigint,
  search_keyword VARCHAR(128) not null,
  search_scope VARCHAR(32) default 'all' not null,
  search_channel VARCHAR(32) default 'miniprogram' not null,
  result_count INTEGER default 0 not null,
  session_token VARCHAR(128),
  client_ip VARCHAR(64),
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  foreign key (search_user_id) references sys_user(id),
  foreign key (keyword_id) references kb_keyword(id),
  check (search_scope in ('all', 'policy', 'faq', 'notice', 'template')),
  check (search_channel in ('miniprogram', 'admin', 'api', 'other')),
  check (result_count >= 0)
);

create index idx_kb_keyword_search_user on kb_keyword_search_history(search_user_id, created_at desc);
create index idx_kb_keyword_search_keyword on kb_keyword_search_history(keyword_id, created_at desc);
create index idx_kb_keyword_search_text on kb_keyword_search_history(search_keyword, created_at desc);

create table party_student_progress (
  id bigint generated by default as identity primary key,
  student_user_id bigint not null,
  flow_id bigint not null,
  current_node_id bigint,
  status VARCHAR(32) default 'in_progress' not null,
  started_at timestamp(6) with time zone,
  updated_node_at timestamp(6) with time zone,
  next_deadline_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (student_user_id, flow_id),
  check (status in ('not_started', 'in_progress', 'paused', 'completed')),
  check (is_deleted in (0, 1)),
  foreign key (student_user_id) references sys_user(id),
  foreign key (flow_id) references party_flow(id),
  foreign key (current_node_id) references party_flow_node(id)
);

create index idx_party_student_progress_deadline on party_student_progress(next_deadline_at);

create table party_reminder_task (
  id bigint generated by default as identity primary key,
  progress_id bigint not null,
  node_id bigint not null,
  due_at timestamp(6) with time zone not null,
  channel VARCHAR(32) default 'miniprogram' not null,
  status VARCHAR(32) default 'pending' not null,
  sent_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  check (channel in ('miniprogram', 'sms', 'email')),
  check (status in ('pending', 'sent', 'canceled', 'failed')),
  foreign key (progress_id) references party_student_progress(id),
  foreign key (node_id) references party_flow_node(id)
);

create index idx_party_reminder_due on party_reminder_task(status, due_at);

create table notice_tag_dict (
  id bigint generated by default as identity primary key,
  tag_code VARCHAR(64) not null,
  tag_name VARCHAR(64) not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  unique (tag_code),
  check (is_deleted in (0, 1))
);

create table notice_item (
  id bigint generated by default as identity primary key,
  title VARCHAR(256) not null,
  content TEXT,
  source_type VARCHAR(32) default 'manual' not null,
  source_name VARCHAR(128),
  source_url VARCHAR(512),
  attachment_file_id bigint,
  publish_at timestamp(6) with time zone,
  created_by bigint,
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  is_deleted INTEGER default 0 not null,
  check (source_type in ('manual', 'crawl', 'import')),
  check (is_deleted in (0, 1)),
  
  foreign key (attachment_file_id) references file_object(id),
  foreign key (created_by) references sys_user(id)
);

create index idx_notice_item_publish on notice_item(publish_at desc);

create table notice_item_tag (
  id bigint generated by default as identity primary key,
  notice_id bigint not null,
  tag_id bigint not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (notice_id, tag_id),
  foreign key (notice_id) references notice_item(id),
  foreign key (tag_id) references notice_tag_dict(id)
);

create table notice_item_keyword (
  id bigint generated by default as identity primary key,
  notice_id bigint not null,
  keyword_id bigint not null,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (notice_id, keyword_id),
  foreign key (notice_id) references notice_item(id),
  foreign key (keyword_id) references kb_keyword(id)
);

create index idx_notice_item_keyword_keyword on notice_item_keyword(keyword_id, notice_id);

create table notice_delivery (
  id bigint generated by default as identity primary key,
  notice_id bigint not null,
  channel VARCHAR(32) not null,
  target_rule_json TEXT,
  status VARCHAR(32) default 'queued' not null,
  scheduled_at timestamp(6) with time zone,
  sent_at timestamp(6) with time zone,
  created_by bigint,
  ext_json TEXT,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  check (channel in ('miniprogram', 'sms', 'email')),
  check (status in ('queued', 'sending', 'done', 'failed', 'canceled')),
  
  
  foreign key (notice_id) references notice_item(id),
  foreign key (created_by) references sys_user(id)
);

create index idx_notice_delivery_status on notice_delivery(status, scheduled_at);

create table notice_delivery_target (
  id bigint generated by default as identity primary key,
  delivery_id bigint not null,
  target_user_id bigint not null,
  status VARCHAR(32) default 'queued' not null,
  sent_at timestamp(6) with time zone,
  error_message TEXT,
  is_read boolean default false not null,
  read_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
  unique (delivery_id, target_user_id),
  check (status in ('queued', 'sent', 'failed', 'canceled')),
  foreign key (delivery_id) references notice_delivery(id),
  foreign key (target_user_id) references sys_user(id)
);

create index idx_notice_delivery_target_status on notice_delivery_target(status, created_at);



