#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue May 26 14:13:01 CST 2026
maven-metadata-aliyunmaven.xml.lastUpdated=1779775981461
maven-metadata-central.xml.lastUpdated=1779775981454
maven-metadata-huaweicloud.xml.lastUpdated=1779775981462
